LineLength:
  Enabled: true
  Max: 100

Tab:
  Enabled: false
  
SymbolSnakeCase:
  Enabled: false

StringLiterals:
  Enabled: false

AsciiComments:
  Enabled: false

SpaceAroundBraces:
  Enabled: false
